server:
  servlet:
    context-path: /reflect

# Spring Application服务名称
spring:
  application:
    name: MyProvider_reflect
# 注册到Eureka
eureka:
  client:
    service-url:
      # eureka 单机版
      #      defaultZone: http://localhost:7001/eureka
      # 集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    # 为Eureka起别名，自定义服务名称
    instance-id: ${spring.application.name}:${server.port}
    # 访问路径显示IP地址
    prefer-ip-address: true

# actuator配置
management:
  endpoints:
    web:
      exposure:
        # 开启所有监控项目,*在YAML中有特殊的含义，所以如果你想包含（或排除）所有的端点，一定要加引号
        include: '*'
    enabled-by-default: true # 启用所有端口

info:
  app.name: MyCloud
  company.name: xlf
  build.artifactId: my_reflect
  build.version: 0.0.1